name: Test Formulae

on: push

jobs:
  brew-install:
    name: Run brew install
    runs-on: ubuntu-latest
    steps:
      - name: Install emacs-gtk
        run: docker run --rm -it -v ${PWD}:/work -u linuxbrew linuxbrew/brew:latest brew install -f /work/Formula/emacs-gtk
