name: Test Formulae

on: push

jobs:
  brew-install:
    name: Run brew install
    strategy:
      matrix:
        package: [emacs-gtk, acl2, isabelle]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install emacs-gtk
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/work -u linuxbrew linuxbrew/brew:latest brew install -v -s -f /work/Formula/${{ matrix.package }}.rb
