name: Test Formulae

on: push

jobs:
  brew-install:
    name: Run brew install
    strategy:
      matrix:
        package:
          - name: emacs-gtk
            options: ''
          - name: neovim
            options: '--HEAD'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ${{ matrix.package }}
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/work -u linuxbrew linuxbrew/brew:latest brew install -v --formula ${{matrix.package.options}} /work/Formula/${{ matrix.package.name }}.rb
