name: Test Formulae

on: push

jobs:
  brew-install:
    name: Run brew install
    runs-on: ubuntu-latest
    steps:
      - name: Tap tani/linux
        run: brew tap tani/linux
      - name: Install emacs-gtk
        run: brew install -f emacs-gtk
